name = "hoon"
entrypoint = "main.hoon"
extensions = [
  "hoon"
]
packages = [
]
setup = [
  "cd /tmp && curl -O https://bootstrap.urbit.org/urbit-linux64-v0.9.2.tgz && tar xzf urbit-linux64-v0.9.2.tgz",
  "mv ./urbit /usr/local/bin/",
  "rm -rf ./urbit*"
]

# [compile]
# command = [
#   "rustc",
#   "-o",
#   "main"
# ]

[run]
command = [
  "urbit",
]

[tests]

  [tests.hello]
  code = "fn main() {\n  println!(\"hello\");\n}"
  output = "hello\n"
