name = "hoon"
entrypoint = "main.hoon"
extensions = [
  "hoon"
]
# packages = [
# ]
setup = [
  "mkdir /tmp/urbit && cd /tmp/urbit && curl -O https://bootstrap.urbit.org/urbit-linux64-v0.9.2.tgz && tar xzf urbit-linux64-v0.9.2.tgz && rm urbit-linux64-v0.9.2.tgz",
  "cd $HOME && mv /tmp/urbit /opt/urbit",
  "/opt/urbit/urbit -t -x -F zod",
]

# [compile]
# command = [
#   "rustc",
#   "-o",
#   "main"
# ]

[run]
command = [
  "/opt/urbit/urbit",
  "zod",
]

# [tests]

#   [tests.hello]
#   code = "fn main() {\n  println!(\"hello\");\n}"
#   output = "hello\n"
