name = "julia"
entrypoint = "main.jl"
extensions = [
  "jl"
]
packages = [
]
setup = [
  "wget https://julialang-s3.julialang.org/bin/linux/x64/1.3/julia-1.3.1-linux-x86_64.tar.gz",
  "tar xf julia-1.3.1-linux-x86_64.tar.gz",
  "cp julia-1.3.1/bin/julia /usr/local/bin/",
  "cp -r julia-1.3.1/lib/* /usr/local/lib/",
  "cp -r julia-1.3.1/include/* /usr/local/include/",
  "cp -r julia-1.3.1/share/* /usr/local/share/",
  "rm -rf ./julia-1.3.1 julia-1.3.1-linux-x86_64.tar.gz",
  "mkdir -p /gocode/src/github.com/replit/",
  "wget https://github.com/replit/prybar/archive/ds-local.zip",
  "unzip ds-local.zip",
  "mv prybar-ds-local /gocode/src/github.com/replit/prybar/",
  "export GOPATH=/gocode",
  "export LC_ALL=C.UTF-8",
  "export PATH=\"/gocode/src/github.com/replit/prybar:$PATH\"",
  "cd /gocode/src/github.com/replit/prybar",
  "make prybar-julia",
  "cp prybar-julia /usr/local/bin/"
]

[run]
command = [
  "prybar-julia",
  "-q",
  "./main.jl"
]

[tests]

  [tests.hello]
  code = "println(\"hello\")"
  output = "hello\n"
