name = "pygame"
entrypoint = "main.py"
extensions = [
  "py"
]
languages = [
  "python3"
]
packages = [
  "gcc",
  "libsdl-ttf2.0-dev",
  "libevent-dev",
  "libportmidi-dev",
  "libsdl1.2-dev",
  "libsdl-image1.2-dev",
  "libsdl-mixer1.2-dev",
  "libtk8.6",
  "xfonts-base",
  "xfonts-100dpi",
  "xfonts-75dpi",
  "xfonts-cyrillic",
  "fontconfig",
  "fonts-freefont-ttf",
  "libfreetype6-dev",
]
popularity = 5.0
setup = [
  "python3 -m pip install pygame pylint==1.6.4 pipreqs-amasad==0.4.10 python-language-server==0.21.5 jedi==0.13.2 pyflakes==2.0.0 rope==0.11.0 yapf==0.25.0 pycodestyle==2.4.0 mccabe==0.6.1 nltk numpy scipy requests bpython ptpython matplotlib==2.2.3",
]
[run]
command = [
  "prybar-python3",
  "-q",
  "main.py"
]

[tests]

  [tests.0]
  code = "print(__name__)"
  output = "__main__\n"

  [tests.hello]
  code = "print(\"hello\")"
  output = "hello\n"

  [tests.pygame]
  code = "import pygame"
  output = "pygame 1.9.6\nHello from the pygame community. https://www.pygame.org/contribute.html\n"

[languageServer]
command = [
  "pyls",
  "-v"
]
