name = "pyxel"
entrypoint = "main.py"
extensions = [
  "py"
]
languages = [
  "python3",
]
packages = [
  "libtk8.6",
  "libevent-dev",
  "gcc",
  "libglfw3-dev",
  "portaudio19-dev",
  "libsdl2-image-2.0-0",
]
popularity = 5.0
setup = [
  "python3 -m pip install -U setuptools configparser",
  "python3 -m pip install pylint==1.6.4 pipreqs-amasad==0.4.10 python-language-server==0.21.5 jedi==0.13.2 pyflakes==2.0.0 rope==0.11.0 yapf==0.25.0 pycodestyle==2.4.0 mccabe==0.6.1 nltk numpy scipy requests bpython ptpython matplotlib==2.2.3 glfw",
  "python3 -m pip install git+https://github.com/amasad/pyxel",
]
[run]
command = [
  "prybar-python3",
  "-q",
  "main.py"
]

[tests]

  [tests.0]
  code = "print(__name__)"
  output = "__main__\n"

  [tests.hello]
  code = "print(\"hello\")"
  output = "hello\n"

  [tests.pyxel]
  code = "import pyxel"
  output = ""

[languageServer]
command = [
  "pyls",
  "-v"
]
